# Generated by Django 3.0.5 on 2021-10-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20211018_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
